server:
  port: 9091
  
spring:
  application:
    name: DEPARTMENT-SERVICE
     
eureka:
 client:
     register-with-eureka: true
     fetch-registry: false
     serviceUrl:
       defaultZone: http://192.168.100.3:8761/eureka/
       
 instance:
  hostname: localhost